name: flutter_music
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.1
  just_audio: ^0.9.46
  rename: ^3.0.2

icons_launcher:
  image_path: "assets/logo/flutter_music_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/music_list.json














